public enum CheckResult {
    ALL_COMMANDS,EMPTY_FIELD,INVALID_USERNAME,ALREADY_LOGGED_IN,SECURITY_QUESTION,INVALID_RESPONSE,PASSWORD_CONFIRMATION,USERNAME_DOESNT_EXIST,SUCCESSFUL_LOGIN,WRONG_PASSWORD,SECONDS_TRY_AGAIN,NEW_PASSWORD,FORGET_PASSWORD_QUESTION,SHOW_USER_INFORMATION,WEAK_PASSWORD,CURRENT_PASSWORD_INCORRECT,NEED_NEW_PASSWORD,PASSWORD_CHANGED_SUCCESSFULLY,INVALID_EMAIL, INVALID_COMMAND, SUCCESSFUL;

    CheckResult() {
    }
//    public static CheckResult[] values() {
//
//    }
//    public static CheckResult valueOf(String ) {
//
//    }


}
