public enum CheckResult {
    ALL_COMMANDS,EMPTY_FIELD,INVALID_USERNAME,ALREADY_LOGGED_IN,SECURITY_QUESTION,INVALID_RESPONSE,PASSWORD_CONFIRMATION,USERNAME_DOESNT_EXIST,SUCCESSFUL_LOGIN,WRONG_PASSWORD,SECONDS_TRY_AGAIN,NEW_PASSWORD,FORGET_PASSWORD_QUESTION,SHOW_USER_INFORMATION,WEAK_PASSWORD,CURRENT_PASSWORD_INCORRECT,NEED_NEW_PASSWORD,PASSWORD_CHANGED_SUCCESSFULLY,INVALID_EMAIL, INVALID_COMMAND, SUCCESSFUL,
    INCORRECT_ADMIN_PASSWORD,ADMIN_COMMANDS,ADMIN_LOGOUT,NEW_CARD_INFO,CARD_EXISTS,PRINT_ALL_CARDS,ENTER_NUMBER,CARD_PROPERTY,BACK_TO_PREVIOUS_MENU,ENTER_NEW_VALUE,ARE_YOU_SURE_EDIT,CARD_NAME_EXISTS,ARE_YOU_SURE_REMOVE,SHOW_ALL_PLAYERS,
    SHOW_PLAYER_COIN,SHOW_PLAYER_CARD;

    CheckResult() {
    }
//    public static CheckResult[] values() {
//
//    }
//    public static CheckResult valueOf(String ) {
//
//    }


}
